# Generated by Django 6.0.1 on 2026-01-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfs',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
            preserve_default=False,
        ),
    ]
