# Generated by Django 6.0.1 on 2026-01-29 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0002_turfs_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='turfs.turfs')),
            ],
            options={
                'db_table': 'turf_images',
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
