# Generated by Django 6.0.1 on 2026-01-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_totol_amount_booking_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.AlterModelTable(
            name='booking',
            table=None,
        ),
    ]
