<<<<<<< HEAD
# Generated by Django 6.0.1 on 2026-01-28 10:23
=======
# Generated by Django 6.0.1 on 2026-01-29 05:36
>>>>>>> main

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
<<<<<<< HEAD
                ('turf_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
=======
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
>>>>>>> main
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sports_type', models.CharField(choices=[('CRICKET', 'Cricket'), ('FOOTBALL', 'Football')], max_length=20)),
                ('location', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
<<<<<<< HEAD
                ('dimension', models.CharField(max_length=100)),
=======
                ('dimension', models.CharField(max_length=50)),
>>>>>>> main
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turfs', to='business.businessuser')),
            ],
            options={
                'db_table': 'turfs',
<<<<<<< HEAD
            },
        ),
        migrations.CreateModel(
            name='TurfImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='turf_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='turf.turf')),
            ],
            options={
                'db_table': 'turf_images',
=======
                'ordering': ['-created_at'],
>>>>>>> main
            },
        ),
    ]
