# Generated by Django 6.0.1 on 2026-01-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='turf',
            name='closing_time',
            field=models.TimeField(default='23:00'),
        ),
        migrations.AddField(
            model_name='turf',
            name='opening_time',
            field=models.TimeField(default='06:00'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(editable=False),
        ),
    ]
