# Generated by Django 6.0.1 on 2026-01-30 08:08

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_turfimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turfimage',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='turfimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='turfimage',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.turf'),
        ),
        migrations.AlterModelTable(
            name='turfimage',
            table=None,
        ),
    ]
