# Generated by Django 6.0.1 on 2026-01-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessUserToken',
        ),
    ]
