# Generated by Django 6.0.1 on 2026-01-29 07:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='turfs.turfs')),
            ],
            options={
                'db_table': 'slots',
                'indexes': [models.Index(fields=['turf', 'slot_date'], name='slots_turf_id_256352_idx'), models.Index(fields=['turf', 'slot_date', 'is_available'], name='slots_turf_id_7ed384_idx')],
                'unique_together': {('turf', 'slot_date', 'start_time', 'end_time')},
            },
        ),
    ]
