# Generated by Django 6.0.1 on 2026-01-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_rename_slot_id_slot_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='slot',
            name='slots_turf_id_256352_idx',
        ),
        migrations.RemoveIndex(
            model_name='slot',
            name='slots_turf_id_7ed384_idx',
        ),
        migrations.AlterField(
            model_name='slot',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
