# Generated by Django 6.0.1 on 2026-02-09 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True, help_text='Optional feedback comment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.booking')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.turf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
                'indexes': [models.Index(fields=['id'], name='feedback_id_idx'), models.Index(fields=['turf'], name='feedback_turf_idx'), models.Index(fields=['user'], name='feedback_user_idx'), models.Index(fields=['booking'], name='feedback_booking_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking',), name='unique_booking_feedback')],
            },
        ),
    ]
