# Generated by Django 6.0.1 on 2026-02-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
