# Generated by Django 6.0.1 on 2026-02-10 05:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_turf_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
    ]
